"""Venue abstraction: interfaces, value objects, and errors.

No adapter lives in this package yet. See :mod:`tradingsys.venues.base` for the
contract an adapter must satisfy.
"""

from tradingsys.venues.base import ExecutionVenue, MarketDataSource, VenueConnection
from tradingsys.venues.enums import (
    CandlePrice,
    Granularity,
    LiquidityRole,
    OrderSide,
    OrderStatus,
    OrderType,
    PositionMode,
    PositionSide,
    TimeInForce,
    TriggerCondition,
)
from tradingsys.venues.errors import (
    InstrumentNotFoundError,
    InsufficientMarginError,
    OrderNotFoundError,
    OrderRejectedError,
    PositionNotFoundError,
    UnsupportedVenueOperationError,
    VenueAuthenticationError,
    VenueConnectivityError,
    VenueError,
    VenueRateLimitError,
    VenueResponseError,
)
from tradingsys.venues.models import (
    AccountSnapshot,
    BookLevel,
    Candle,
    CredentialRefresh,
    ExecutionEvent,
    Fill,
    FundingRate,
    Order,
    OrderBook,
    OrderRequest,
    Position,
    Quote,
    SwapRates,
    Trade,
    VenueCapabilities,
)

__all__ = [
    "AccountSnapshot",
    "BookLevel",
    "Candle",
    "CandlePrice",
    "CredentialRefresh",
    "ExecutionEvent",
    "ExecutionVenue",
    "Fill",
    "FundingRate",
    "Granularity",
    "InstrumentNotFoundError",
    "InsufficientMarginError",
    "LiquidityRole",
    "MarketDataSource",
    "Order",
    "OrderBook",
    "OrderNotFoundError",
    "OrderRejectedError",
    "OrderRequest",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "Position",
    "PositionMode",
    "PositionNotFoundError",
    "PositionSide",
    "Quote",
    "SwapRates",
    "TimeInForce",
    "Trade",
    "TriggerCondition",
    "UnsupportedVenueOperationError",
    "VenueAuthenticationError",
    "VenueCapabilities",
    "VenueConnection",
    "VenueConnectivityError",
    "VenueError",
    "VenueRateLimitError",
    "VenueResponseError",
]
