"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from tradingsys.venues.ctrader.messages import OpenApiCommonModelMessages_pb2 as _OpenApiCommonModelMessages_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ProtoMessage(_message.Message):
    """* Base message that is used for all messages that are sent to/from Open API proxy of cTrader platform."""

    DESCRIPTOR: _descriptor.Descriptor

    PAYLOADTYPE_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    CLIENTMSGID_FIELD_NUMBER: _builtins.int
    payloadType: _builtins.int
    """Contains id of ProtoPayloadType or other custom PayloadTypes (e.g. ProtoOAPayloadType)."""
    payload: _builtins.bytes
    """Serialized protobuf message that corresponds to payloadType."""
    clientMsgId: _builtins.str
    """Request message id, assigned by the client that will be returned in the response."""
    def __init__(
        self,
        *,
        payloadType: _builtins.int | None = ...,
        payload: _builtins.bytes | None = ...,
        clientMsgId: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clientMsgId", b"clientMsgId", "payload", b"payload", "payloadType", b"payloadType"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clientMsgId", b"clientMsgId", "payload", b"payload", "payloadType", b"payloadType"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProtoMessage: _TypeAlias = ProtoMessage  # noqa: Y015

@_typing.final
class ProtoErrorRes(_message.Message):
    """* Error response that is sent from Open API proxy when error occurs."""

    DESCRIPTOR: _descriptor.Descriptor

    PAYLOADTYPE_FIELD_NUMBER: _builtins.int
    ERRORCODE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    MAINTENANCEENDTIMESTAMP_FIELD_NUMBER: _builtins.int
    payloadType: _OpenApiCommonModelMessages_pb2.ProtoPayloadType.ValueType
    errorCode: _builtins.str
    """Contains name of ProtoErrorCode or other custom ErrorCodes (e.g. ProtoCHErrorCode)."""
    description: _builtins.str
    """Error description."""
    maintenanceEndTimestamp: _builtins.int
    """The Unix time in milliseconds of the end of the maintenance."""
    def __init__(
        self,
        *,
        payloadType: _OpenApiCommonModelMessages_pb2.ProtoPayloadType.ValueType | None = ...,
        errorCode: _builtins.str | None = ...,
        description: _builtins.str | None = ...,
        maintenanceEndTimestamp: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "errorCode", b"errorCode", "maintenanceEndTimestamp", b"maintenanceEndTimestamp", "payloadType", b"payloadType"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "errorCode", b"errorCode", "maintenanceEndTimestamp", b"maintenanceEndTimestamp", "payloadType", b"payloadType"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProtoErrorRes: _TypeAlias = ProtoErrorRes  # noqa: Y015

@_typing.final
class ProtoHeartbeatEvent(_message.Message):
    """* Event that is sent from Open API proxy and can be used as criteria that connection is healthy when no other messages are sent by cTrader platform. Open API client can send this message when he needs to keep the connection open for a period without other messages longer than 30 seconds."""

    DESCRIPTOR: _descriptor.Descriptor

    PAYLOADTYPE_FIELD_NUMBER: _builtins.int
    payloadType: _OpenApiCommonModelMessages_pb2.ProtoPayloadType.ValueType
    def __init__(
        self,
        *,
        payloadType: _OpenApiCommonModelMessages_pb2.ProtoPayloadType.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["payloadType", b"payloadType"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payloadType", b"payloadType"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProtoHeartbeatEvent: _TypeAlias = ProtoHeartbeatEvent  # noqa: Y015
