"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ProtoPayloadType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ProtoPayloadTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ProtoPayloadType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PROTO_MESSAGE: _ProtoPayloadType.ValueType  # 5
    """common intensive"""
    ERROR_RES: _ProtoPayloadType.ValueType  # 50
    """common commands"""
    HEARTBEAT_EVENT: _ProtoPayloadType.ValueType  # 51

class ProtoPayloadType(_ProtoPayloadType, metaclass=_ProtoPayloadTypeEnumTypeWrapper):
    """--- INTENSIVE COMMANDS 1 - 49
    --- COMMON API 50 - 69
    """

PROTO_MESSAGE: ProtoPayloadType.ValueType  # 5
"""common intensive"""
ERROR_RES: ProtoPayloadType.ValueType  # 50
"""common commands"""
HEARTBEAT_EVENT: ProtoPayloadType.ValueType  # 51
Global___ProtoPayloadType: _TypeAlias = ProtoPayloadType  # noqa: Y015

class _ProtoErrorCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ProtoErrorCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ProtoErrorCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN_ERROR: _ProtoErrorCode.ValueType  # 1
    """Generic error."""
    UNSUPPORTED_MESSAGE: _ProtoErrorCode.ValueType  # 2
    """Message is not supported. Wrong message."""
    INVALID_REQUEST: _ProtoErrorCode.ValueType  # 3
    """Generic error.  Usually used when input value is not correct."""
    TIMEOUT_ERROR: _ProtoErrorCode.ValueType  # 5
    """Deal execution is reached timeout and rejected."""
    ENTITY_NOT_FOUND: _ProtoErrorCode.ValueType  # 6
    """Generic error for requests by id."""
    CANT_ROUTE_REQUEST: _ProtoErrorCode.ValueType  # 7
    """Connection to Server is lost or not supported."""
    FRAME_TOO_LONG: _ProtoErrorCode.ValueType  # 8
    """Message is too large."""
    MARKET_CLOSED: _ProtoErrorCode.ValueType  # 9
    """Market is closed."""
    CONCURRENT_MODIFICATION: _ProtoErrorCode.ValueType  # 10
    """Order is blocked (e.g. under execution) and change cannot be applied."""
    BLOCKED_PAYLOAD_TYPE: _ProtoErrorCode.ValueType  # 11
    """Message is blocked by server or rate limit is reached."""

class ProtoErrorCode(_ProtoErrorCode, metaclass=_ProtoErrorCodeEnumTypeWrapper):
    """COMMON error codes 1 - 99"""

UNKNOWN_ERROR: ProtoErrorCode.ValueType  # 1
"""Generic error."""
UNSUPPORTED_MESSAGE: ProtoErrorCode.ValueType  # 2
"""Message is not supported. Wrong message."""
INVALID_REQUEST: ProtoErrorCode.ValueType  # 3
"""Generic error.  Usually used when input value is not correct."""
TIMEOUT_ERROR: ProtoErrorCode.ValueType  # 5
"""Deal execution is reached timeout and rejected."""
ENTITY_NOT_FOUND: ProtoErrorCode.ValueType  # 6
"""Generic error for requests by id."""
CANT_ROUTE_REQUEST: ProtoErrorCode.ValueType  # 7
"""Connection to Server is lost or not supported."""
FRAME_TOO_LONG: ProtoErrorCode.ValueType  # 8
"""Message is too large."""
MARKET_CLOSED: ProtoErrorCode.ValueType  # 9
"""Market is closed."""
CONCURRENT_MODIFICATION: ProtoErrorCode.ValueType  # 10
"""Order is blocked (e.g. under execution) and change cannot be applied."""
BLOCKED_PAYLOAD_TYPE: ProtoErrorCode.ValueType  # 11
"""Message is blocked by server or rate limit is reached."""
Global___ProtoErrorCode: _TypeAlias = ProtoErrorCode  # noqa: Y015
